apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalibrator
  labels:
    app: excalibrator
spec:
  selector:
    matchLabels:
      app: excalibrator
  template:
    metadata:
      labels:
        app: excalibrator
    spec:
      containers:
        - name: excalibrator
          image: excalibrator
          ports:
            - name: excalibrator
              containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalibrator-web
  labels:
    app: excalibrator-web
spec:
  selector:
    matchLabels:
      app: excalibrator-web
  template:
    metadata:
      labels:
        app: excalibrator-web
    spec:
      containers:
        - name: excalibrator-web
          image: excalibrator-web
          ports:
            - name: excalibrator-web
              containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalibrator-api
  labels:
    app: excalibrator-api
spec:
  selector:
    matchLabels:
      app: excalibrator-api
  template:
    metadata:
      labels:
        app: excalibrator-api
    spec:
      containers:
        - name: excalibrator-api
          image: excalibrator-api
          ports:
            - name: excalibrator-api
              containerPort: 8000
