apiVersion: v1
kind: Service
metadata:
  name: excalibrator
  labels:
    app: excalibrator
spec:
  ports:
    - name: excalibrator
      port: 3000
      protocol: TCP
      targetPort: excalibrator
  selector:
    app: excalibrator
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: excalibrator-web
  labels:
    app: excalibrator-web
spec:
  ports:
    - name: excalibrator-web
      port: 80
      protocol: TCP
      targetPort: excalibrator-web
  selector:
    app: excalibrator-web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: excalibrator-api
  labels:
    app: excalibrator-api
spec:
  ports:
    - name: excalibrator-api
      port: 80
      protocol: TCP
      targetPort: excalibrator-api
  selector:
    app: excalibrator-api
  type: ClusterIP
