apiVersion: v1
kind: Service
metadata:
  name: hanbaiki
  labels:
    app: hanbaiki
spec:
  ports:
    - name: hanbaiki
      port: 3000
      protocol: TCP
      targetPort: hanbaiki
  selector:
    app: hanbaiki
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hanbaiki-web
  labels:
    app: hanbaiki-web
spec:
  ports:
    - name: hanbaiki-web
      port: 80
      protocol: TCP
      targetPort: hanbaiki-web
  selector:
    app: hanbaiki-web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hanbaiki-api
  labels:
    app: hanbaiki-api
spec:
  ports:
    - name: hanbaiki-api
      port: 80
      protocol: TCP
      targetPort: hanbaiki-api
  selector:
    app: hanbaiki-api
  type: ClusterIP
